use_frameworks!

target 'WHIX' do
  pod 'Firebase/Core'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod "SwiftyCam"
  pod 'iOSPhotoEditor'
  pod 'Disk'
  pod 'SDWebImage'
end
